Messages:
  DontHavePermission: "&cYou don't have permission."
  NotAvailable: "&cNot available in this world."
  ConfigReloaded: "&aConfig has been reloaded."
  Help:
    Help: "Show this help."
    Show: "Show title of this world."
    Reload: "Reload config file."

# Time to display the title (Unit: seconds)
# Notice: ActionBar has no effect
DefaultTime:
  fadein: 0.5
  stay: 1.75
  fadeout: 0.5

Worlds:
  world:
    title: "&2World"
  world_nether:
    title: "&cNether"
    subtitle: "world_nether"
  world_the_end:
    title: "&8The End"
    subtitle: "&kworld_the_end"
    actionbar: "vs EnderDragon"
# Syntax ------>
#  world_name:
#    title: "maintitle message."
#    subtitle: "&c&o&l&o&r&c&o&d&e subtitle message.(&&escape is &&)"
#    actionbar: "actionbar message"
#    # Overrides
#    fadein: 0.5
#    stay: 1.75
#    fadeout: 0.5
# <------ Syntax
# Color code is lowercase.
