main: "jp.jyn.thisworld.ThisWorld"
name: "${project.artifactId}"
version: "${project.version}"
website: "https://github.com/HimaJyun/ThisWorld"
author: '@HimaJyun'
api-version: 1.13

commands:
    thisworld:
        description: 'Show this world name.'
        aliases: tw

permissions:
    thisworld.show:
        default: true
    thisworld.reload:
        default: op
